"""
Bearer Token (API Key) Authentication Realm for Nexus Repository.

This module implements API key authentication (Feature F-304) as the
second realm in the multi-backend authentication chain:

    local → **bearer_token** → jwt → ldap → sso

It replaces ``BearerTokenRealm`` from the Java source system's Apache
Shiro 2.0.0 framework (AAP Sections 0.2.2, 0.8.5).

**Authentication Flow:**

1. A client sends an ``Authorization: Bearer <token>`` header.
2. The authentication chain calls :meth:`supports` — this realm returns
   ``True`` only if the token does **not** look like a JWT (i.e. does not
   contain exactly two dots).
3. :meth:`authenticate` hashes the incoming token with SHA-256 and
   iterates through all stored API key hashes for every user, using
   ``hmac.compare_digest`` for **timing-safe** comparison.
4. If a match is found, the realm checks:
   - User account status (must be ``'active'``).
   - API key expiration (``expires_at`` field, if set).
5. On success, the ``last_used`` timestamp is updated for audit tracking
   (Feature F-303), and the ``User`` object is returned.
6. On failure, ``None`` is returned so the JWT realm (position 3) can try.

**API Key Storage Model:**

API keys are stored in the ``User.attributes`` JSON column under the
``'api_keys'`` key as a list of dictionaries::

    user.attributes = {
        "api_keys": [
            {
                "key_hash":    "<sha256-hex-digest>",
                "created_at":  "<iso-8601-utc>",
                "description": "<user-provided label>",
                "last_used":   "<iso-8601-utc> | null",
                "expires_at":  "<iso-8601-utc> | null",
            },
            ...
        ]
    }

Only the SHA-256 hash of the key is stored — the plaintext is returned
**exactly once** upon creation and is never persisted or logged.

**Security Invariants:**

- API key values (plaintext *or* hash) are **NEVER** logged.
- All hash comparisons use ``hmac.compare_digest`` to prevent timing attacks.
- SHA-256 is sufficient for API keys because they are high-entropy tokens
  generated by ``secrets.token_hex`` (unlike passwords).

**Architecture Context:**

- Extends :class:`~src.app.auth.realms.RealmBase` (AAP Section 0.4.3,
  Chain of Responsibility pattern).
- Uses :func:`~src.app.auth.password_utils.generate_api_key` for
  cryptographically secure key generation (``secrets`` module).
- Uses :attr:`~src.app.extensions.db` for session management via
  ``db.session.commit()``.
- Accesses :attr:`flask.current_app` for runtime configuration.
- Python 3.12+ with complete type annotations (AAP Section 0.7.2).
"""

from __future__ import annotations

import hashlib
import hmac
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from flask import current_app

from src.app.auth.password_utils import generate_api_key
from src.app.auth.realms import RealmBase
from src.app.extensions import db
from src.app.models.user import User

# ---------------------------------------------------------------------------
# Module-Level Logger
# ---------------------------------------------------------------------------
# Replaces SLF4J 1.7.36 + Logback 1.2.13 from the Java source system.
# SECURITY: Never logs plaintext or hashed API key values.
# ---------------------------------------------------------------------------

logger: logging.Logger = logging.getLogger(__name__)


# ===========================================================================
# BearerTokenRealm
# ===========================================================================


class BearerTokenRealm(RealmBase):
    """API key authentication realm (Feature F-304).

    This is realm position **2** in the authentication chain:
    ``local → bearer_token → jwt → ldap → sso``.

    Replaces ``BearerTokenRealm`` from the Java source system's Apache
    Shiro 2.0.0 framework.  Uses a first-successful strategy: if the
    token matches a stored API key, authentication stops; otherwise the
    token is passed to the next realm (JWT).

    Class Attributes:
        REALM_NAME: Unique identifier used in logging, configuration, and
            the :class:`~src.app.auth.realms.RealmRegistry`.
        SUPPORTED_CREDENTIAL_TYPES: Credential types this realm handles.
        API_KEY_PREFIX: Conventional prefix for Nexus-generated API keys
            (used for display/identification, not for authentication logic).
    """

    REALM_NAME: str = "bearer_token"
    SUPPORTED_CREDENTIAL_TYPES: List[str] = ["bearer_token"]

    # Nexus API key prefix — informational label for key identification.
    API_KEY_PREFIX: str = "NX"

    # Default maximum API keys per user (overridable via app config).
    _DEFAULT_MAX_KEYS_PER_USER: int = 10

    # Minimum interval (seconds) between last_used timestamp updates to
    # avoid excessive DB writes on high-frequency API key usage.
    _LAST_USED_UPDATE_INTERVAL_SECONDS: int = 60

    def __init__(self) -> None:
        """Initialise the Bearer Token realm.

        Calls the parent ``RealmBase.__init__`` which sets up a
        per-class structured logger, then initialises a private
        attribute used to track the matched API key entry across
        the authenticate → validate → update pipeline.
        """
        super().__init__()
        # Tracks the matched API key entry dict during the current
        # authenticate() call so that _is_api_key_expired() and
        # _update_api_key_last_used() can reference the specific key.
        self._matched_key_entry: Optional[Dict[str, Any]] = None

    # ------------------------------------------------------------------
    # RealmBase Abstract Interface Implementation
    # ------------------------------------------------------------------

    def authenticate(self, credentials: Dict[str, Any]) -> Optional[User]:
        """Attempt authentication using an API key token.

        Implements the :class:`RealmBase` contract.  Extracts the
        ``'token'`` value from *credentials*, verifies it against stored
        API key hashes, checks user status and key expiration, updates
        the ``last_used`` audit trail, and returns the matching
        :class:`User` on success.

        Args:
            credentials: Dictionary containing authentication data.
                Expected key: ``'token'`` — the bearer token string.

        Returns:
            The authenticated :class:`User` if the API key is valid and
            the account is active; ``None`` otherwise (allowing the next
            realm in the chain to try).
        """
        # Reset per-request matched key tracking.
        self._matched_key_entry = None

        token: Optional[str] = credentials.get("token")
        if not token:
            return None

        # JWT tokens have exactly 2 dots (header.payload.signature).
        # API keys are hex strings without dots — skip JWTs early.
        if token.count(".") == 2:
            return None

        # Look up user by API key (timing-safe comparison internally).
        user: Optional[User] = self._find_user_by_api_key(token)
        if user is None:
            self.logger.debug("API key authentication failed: key not found")
            return None

        # Verify that the account is active.
        if user.status != "active":
            self.logger.warning(
                "API key auth attempt for inactive user: %s", user.user_id
            )
            self._matched_key_entry = None
            return None

        # Check whether the matched API key has expired.
        if self._is_api_key_expired(user):
            self.logger.warning(
                "Expired API key used for user: %s", user.user_id
            )
            self._matched_key_entry = None
            return None

        # Update the last_used timestamp for audit tracking (F-303).
        self._update_api_key_last_used(user)

        self.logger.info(
            "API key authentication successful for user: %s", user.user_id
        )
        return user

    def supports(self, credentials: Dict[str, Any]) -> bool:
        """Check whether this realm can handle the given credentials.

        Returns ``True`` when *credentials* contains a ``'token'`` value
        that does **not** look like a JWT (i.e. does not have exactly
        two dot separators).

        Args:
            credentials: Dictionary containing authentication data.

        Returns:
            ``True`` if the credentials appear to be an API key;
            ``False`` otherwise.
        """
        token: Optional[str] = credentials.get("token")
        if not token or not isinstance(token, str):
            return False
        # JWTs have exactly 2 dots — those belong to the JWT realm.
        if token.count(".") == 2:
            return False
        return True

    def get_realm_name(self) -> str:
        """Return the unique name identifier for this realm.

        Returns:
            ``'bearer_token'`` — used for logging, config look-ups, and
            ordering in the authentication chain.
        """
        return self.REALM_NAME

    # ------------------------------------------------------------------
    # Optional Override
    # ------------------------------------------------------------------

    def is_configured(self) -> bool:
        """Check whether API key authentication is available.

        The bearer token realm is always considered configured because it
        does not depend on external services (unlike LDAP or SSO realms).
        API keys are stored directly in the application database.

        Returns:
            Always ``True``.
        """
        return True

    # ------------------------------------------------------------------
    # API Key Management — Public Methods
    # ------------------------------------------------------------------

    def create_api_key(
        self, user: User, description: str = ""
    ) -> str:
        """Generate a new API key for *user* and persist the hash.

        Uses :func:`~src.app.auth.password_utils.generate_api_key` for
        cryptographically secure random generation.  The SHA-256 hash of
        the key is stored in the user's ``attributes['api_keys']`` list;
        the plaintext key is returned **exactly once** and is never
        persisted or logged.

        Args:
            user: The :class:`User` to create the API key for.
            description: Optional human-readable label for the key.

        Returns:
            The plaintext API key string (returned only this once).

        Raises:
            ValueError: If the user has reached the maximum allowed number
                of API keys.
        """
        # Determine maximum keys per user from app config (with fallback).
        try:
            max_keys: int = current_app.config.get(
                "MAX_API_KEYS_PER_USER", self._DEFAULT_MAX_KEYS_PER_USER
            )
        except RuntimeError:
            # Outside of application context (e.g. during testing).
            max_keys = self._DEFAULT_MAX_KEYS_PER_USER

        # Read current API keys from user attributes.
        attrs: Dict[str, Any] = dict(user.attributes or {})
        api_keys: List[Dict[str, Any]] = list(attrs.get("api_keys", []))

        # Enforce per-user key limit.
        if len(api_keys) >= max_keys:
            raise ValueError(
                f"User '{user.user_id}' has reached the maximum of "
                f"{max_keys} API keys. Revoke an existing key first."
            )

        # Generate a new cryptographically secure API key.
        plaintext_key: str = generate_api_key(length=40)
        key_hash: str = self._hash_api_key(plaintext_key)

        # Build the key entry for storage.
        key_entry: Dict[str, Any] = {
            "key_hash": key_hash,
            "created_at": datetime.now(tz=timezone.utc).isoformat(),
            "description": description,
            "last_used": None,
            "expires_at": None,  # None = never expires
        }
        api_keys.append(key_entry)
        attrs["api_keys"] = api_keys

        # Reassign the entire attributes dict to trigger SQLAlchemy's
        # JSON mutation tracking (required for portable JSON columns).
        user.attributes = attrs
        db.session.commit()

        self.logger.info(
            "Created new API key for user '%s' (description: '%s')",
            user.user_id,
            description,
        )
        # SECURITY: Return the plaintext key ONCE — never store or log it.
        return plaintext_key

    def revoke_api_key(self, user: User, key_hash: str) -> bool:
        """Revoke (remove) an API key identified by its hash.

        Args:
            user: The :class:`User` whose key should be revoked.
            key_hash: The SHA-256 hex digest of the key to revoke.

        Returns:
            ``True`` if the key was found and removed; ``False`` if no
            matching key was found.
        """
        attrs: Dict[str, Any] = dict(user.attributes or {})
        api_keys: List[Dict[str, Any]] = list(attrs.get("api_keys", []))
        original_count: int = len(api_keys)

        # Filter out the key with the matching hash.
        api_keys = [
            entry for entry in api_keys
            if not hmac.compare_digest(
                entry.get("key_hash", ""), key_hash
            )
        ]

        if len(api_keys) == original_count:
            self.logger.debug(
                "API key revocation failed for user '%s': key not found",
                user.user_id,
            )
            return False

        attrs["api_keys"] = api_keys

        # Reassign for SQLAlchemy JSON mutation tracking.
        user.attributes = attrs
        db.session.commit()

        self.logger.info(
            "Revoked API key for user '%s'", user.user_id
        )
        return True

    def list_api_keys(self, user: User) -> List[Dict[str, Any]]:
        """Return metadata for all of *user*'s API keys.

        The returned dictionaries include ``description``, ``created_at``,
        ``last_used``, and ``expires_at`` — but **NEVER** the
        ``key_hash`` (security requirement).

        Args:
            user: The :class:`User` whose API keys to list.

        Returns:
            A list of dictionaries containing redacted API key metadata.
            Each entry includes a positional ``'id'`` for reference in
            revocation operations and a masked ``'key_preview'`` showing
            only the hash prefix.
        """
        attrs: Dict[str, Any] = user.attributes or {}
        api_keys: List[Dict[str, Any]] = attrs.get("api_keys", [])

        result: List[Dict[str, Any]] = []
        for idx, entry in enumerate(api_keys):
            # Provide a safe preview: first 8 chars of hash + ellipsis.
            raw_hash: str = entry.get("key_hash", "")
            key_preview: str = (
                f"{raw_hash[:8]}..." if len(raw_hash) >= 8 else "****"
            )
            result.append(
                {
                    "id": idx,
                    "description": entry.get("description", ""),
                    "created_at": entry.get("created_at"),
                    "last_used": entry.get("last_used"),
                    "expires_at": entry.get("expires_at"),
                    "key_preview": key_preview,
                }
            )
        return result

    # ------------------------------------------------------------------
    # Private — API Key Lookup
    # ------------------------------------------------------------------

    def _find_user_by_api_key(self, api_key: str) -> Optional[User]:
        """Search for a user whose stored API key hash matches *api_key*.

        Hashes the incoming key with SHA-256 and iterates through every
        user that has API keys stored in their ``attributes`` JSON
        column, comparing hashes with ``hmac.compare_digest`` for
        timing-safety.

        On a match, sets ``self._matched_key_entry`` so that downstream
        methods (:meth:`_is_api_key_expired`, :meth:`_update_api_key_last_used`)
        can reference the specific key entry.

        Args:
            api_key: The plaintext API key token to look up.

        Returns:
            The matching :class:`User`, or ``None`` if no match is found.
        """
        incoming_hash: str = self._hash_api_key(api_key)

        try:
            # Query all users that potentially have API keys.
            # We filter for non-null attributes at the application level
            # for maximum portability across SQLite and PostgreSQL.
            users: List[User] = User.query.filter(
                User.attributes.isnot(None)
            ).all()
        except Exception:
            self.logger.exception(
                "Database error while querying users for API key authentication"
            )
            return None

        for user in users:
            user_api_keys: List[Dict[str, Any]] = (
                (user.attributes or {}).get("api_keys", [])
            )
            for key_entry in user_api_keys:
                stored_hash: str = key_entry.get("key_hash", "")
                # CRITICAL: timing-safe comparison to prevent side-channel attacks.
                if hmac.compare_digest(stored_hash, incoming_hash):
                    self._matched_key_entry = key_entry
                    return user

        return None

    # ------------------------------------------------------------------
    # Private — Hashing
    # ------------------------------------------------------------------

    @staticmethod
    def _hash_api_key(api_key: str) -> str:
        """Compute the SHA-256 hex digest of *api_key*.

        SHA-256 is appropriate for API keys (unlike passwords) because
        they are high-entropy random tokens generated by ``secrets``.
        The resulting hash is used for storage and timing-safe comparison.

        Args:
            api_key: The plaintext API key to hash.

        Returns:
            A 64-character lowercase hexadecimal string.
        """
        return hashlib.sha256(api_key.encode("utf-8")).hexdigest()

    # ------------------------------------------------------------------
    # Private — Validation Helpers
    # ------------------------------------------------------------------

    def _is_api_key_expired(self, user: User) -> bool:
        """Check whether the matched API key has expired.

        Reads the ``expires_at`` field from the key entry that was matched
        during :meth:`_find_user_by_api_key`.  Returns ``False`` (valid)
        if no expiration is set (``None``), if the key entry is missing,
        or if the expiration date has not yet passed.

        Args:
            user: The :class:`User` whose matched key is being checked.
                (Provided for logging context; the actual key entry is
                taken from ``self._matched_key_entry``.)

        Returns:
            ``True`` if the key has expired; ``False`` otherwise.
        """
        if self._matched_key_entry is None:
            return False

        expires_at_raw: Optional[str] = self._matched_key_entry.get("expires_at")
        if expires_at_raw is None:
            # No expiration set — key is valid indefinitely.
            return False

        try:
            expires_at: datetime = datetime.fromisoformat(expires_at_raw)
            # Ensure timezone-aware comparison.
            if expires_at.tzinfo is None:
                expires_at = expires_at.replace(tzinfo=timezone.utc)
            now: datetime = datetime.now(tz=timezone.utc)
            return now >= expires_at
        except (ValueError, TypeError):
            self.logger.warning(
                "Invalid expires_at format for API key of user '%s'; "
                "treating key as non-expired",
                user.user_id,
            )
            return False

    def _update_api_key_last_used(self, user: User) -> None:
        """Update the ``last_used`` timestamp on the matched API key.

        Tracks API key usage for audit logging (Feature F-303).  To avoid
        excessive database writes under heavy API key usage, the timestamp
        is only updated if the previous ``last_used`` value is older than
        :attr:`_LAST_USED_UPDATE_INTERVAL_SECONDS` (default: 60 seconds).

        Args:
            user: The :class:`User` whose matched key should be updated.
        """
        if self._matched_key_entry is None:
            return

        now: datetime = datetime.now(tz=timezone.utc)
        now_iso: str = now.isoformat()

        # Check if we should skip the update to reduce DB write frequency.
        last_used_raw: Optional[str] = self._matched_key_entry.get("last_used")
        if last_used_raw is not None:
            try:
                last_used: datetime = datetime.fromisoformat(last_used_raw)
                if last_used.tzinfo is None:
                    last_used = last_used.replace(tzinfo=timezone.utc)
                elapsed: float = (now - last_used).total_seconds()
                if elapsed < self._LAST_USED_UPDATE_INTERVAL_SECONDS:
                    return  # Skip — too recent to warrant a DB write.
            except (ValueError, TypeError):
                pass  # Proceed with update if parsing fails.

        # Locate the matching key entry in the user's attributes and
        # update its last_used timestamp.
        try:
            attrs: Dict[str, Any] = dict(user.attributes or {})
            api_keys: List[Dict[str, Any]] = attrs.get("api_keys", [])

            # Build a new list with the matched entry updated — this
            # ensures a truly new Python object graph for SQLAlchemy's
            # JSON column change detection.
            updated_keys: List[Dict[str, Any]] = []
            matched_hash: str = self._matched_key_entry.get("key_hash", "")
            for key_entry in api_keys:
                # Deep-copy each entry to break object identity
                new_entry: Dict[str, Any] = dict(key_entry)
                stored_hash: str = new_entry.get("key_hash", "")
                if hmac.compare_digest(stored_hash, matched_hash):
                    new_entry["last_used"] = now_iso
                updated_keys.append(new_entry)

            attrs["api_keys"] = updated_keys

            # Reassign for SQLAlchemy JSON mutation tracking and
            # explicitly add to session for reliable dirty detection.
            user.attributes = attrs
            db.session.add(user)
            db.session.commit()
        except Exception:
            self.logger.exception(
                "Failed to update last_used timestamp for API key of "
                "user '%s'",
                user.user_id,
            )
